<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3.2 (Python 3.11.3 on win32)" generated="2025-10-18T17:11:08.709247" rpa="false" schemaversion="5">
<suite id="s1" name="Login" source="C:\Users\GENIUS\IdeaProjects\PourEntreprise\tests\ui\Login.robot">
<test id="s1-t1" name="Lancer La connexion" line="6">
<kw name="Se connecter">
<msg time="2025-10-18T17:11:08.740070" level="FAIL">No keyword with name 'Se connecter' found.</msg>
<status status="FAIL" start="2025-10-18T17:11:08.739071" elapsed="0.000999">No keyword with name 'Se connecter' found.</status>
</kw>
<status status="FAIL" start="2025-10-18T17:11:08.737651" elapsed="0.002419">No keyword with name 'Se connecter' found.</status>
</test>
<status status="FAIL" start="2025-10-18T17:11:08.711302" elapsed="0.028768"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Login" id="s1" pass="0" fail="1" skip="0">Login</stat>
</suite>
</statistics>
<errors>
<msg time="2025-10-18T17:11:08.736649" level="ERROR">Error in file 'C:\Users\GENIUS\IdeaProjects\PourEntreprise\tests\ui\Login.robot' on line 2: Resource file '..\resources\keywords\Login.robot' does not exist.</msg>
</errors>
</robot>
